use customer_behavior;
select * from customer limit 20;

-- Q1) what is the total revenue generated by male vs female customer

select gender,sum(purchase_amount) from customer
group by gender;  


select customer_id,purchase_amount from customer
where discount_applied = 'yes' and purchase_amount >= (select avg(purchase_amount) from customer);


select * from customer limit 5;

-- Q3) Whate are the top 5 product with the  highest average review rating 
select item_purchased,round(avg(review_rating),2) from customer 
group by item_purchased
order by avg(review_rating) desc
limit 5; 	

-- Q4) Compare the average purchese amount between standard and express shipping

select  shipping_type,avg(purchase_amount) from customer 
where  shipping_type in ('Express','Standard') 
group by shipping_type;

-- Q5) Do subscribed customer spend more? compare average spend and total revenue between subscribers and non-subscribed

select 
subscription_status,
count(customer_id) as customer_id,
avg(purchase_amount) as avg_spend,
sum(purchase_amount) as total_revanve from customer
group by subscription_status;

-- Q6) which 5 products have the higest percentage with discounts applied



select item_purchased,
round(SUM(case when discount_applied = 'yes' then 1 else 0 end)/count(*) * 100,2)  as discount_rate from customer
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7) segment customer into new, returning and layal based on their total 
-- number of previous purchases,and show the count of each segment



WITH customer_type AS (
    SELECT 
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)
SELECT 
    customer_segment,
    COUNT(*) AS `Number of Customers`
FROM customer_type
GROUP BY customer_segment;

-- Q8 what are the top 3 most purchased products within each category

select * from customer limit 5;

select 
	category,
    item_purchased,
    sum(purchase_amount) as total_purchase
    
from customer
group by category
order by total_purchase desc
limit 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;

